#!/usr/bin/env bash
# ============================================================================
# deploy-demo.sh — Script deploy SWAAP dengan HTTPS (Let's Encrypt)
# Alternatif tanpa Cloudflare Tunnel, untuk presentasi / demo.
#
# Cara pakai:
#   chmod +x deploy-demo.sh
#   sudo ./deploy-demo.sh
#
# Script ini akan:
#   1. Minta input domain & email
#   2. Generate file .env
#   3. Generate nginx config dari template
#   4. Request SSL certificate via Certbot (standalone)
#   5. Build & jalankan semua container
# ============================================================================

set -e

# ── Warna output ──────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${CYAN}"
echo "╔══════════════════════════════════════════════════════════════╗"
echo "║           SWAAP Demo Deployment (HTTPS + Domain)            ║"
echo "║           Tanpa Cloudflare — pakai Let's Encrypt            ║"
echo "╚══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# ── Check root / sudo ─────────────────────────────────────────────────────────
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}[ERROR] Script ini harus dijalankan dengan sudo!${NC}"
    echo "  Jalankan: sudo ./deploy-demo.sh"
    exit 1
fi

# ── Check dependencies ────────────────────────────────────────────────────────
echo -e "${YELLOW}[1/6] Mengecek dependencies...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}[ERROR] Docker belum terinstall!${NC}"
    echo "  Install: https://docs.docker.com/engine/install/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo -e "${RED}[ERROR] Docker Compose V2 belum terinstall!${NC}"
    echo "  Install: https://docs.docker.com/compose/install/"
    exit 1
fi

echo -e "${GREEN}  ✓ Docker & Docker Compose tersedia${NC}"

# ── Input dari user ───────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[2/6] Masukkan informasi deployment:${NC}"
echo ""

read -rp "  Domain (contoh: swaap.example.com): " DOMAIN
while [ -z "$DOMAIN" ]; do
    echo -e "${RED}  Domain tidak boleh kosong!${NC}"
    read -rp "  Domain (contoh: swaap.example.com): " DOMAIN
done

read -rp "  Email untuk SSL (contoh: admin@example.com): " EMAIL
while [ -z "$EMAIL" ]; do
    echo -e "${RED}  Email tidak boleh kosong!${NC}"
    read -rp "  Email untuk SSL (contoh: admin@example.com): " EMAIL
done

echo ""
echo -e "${CYAN}  ┌─────────────────────────────────────┐"
echo -e "  │  Domain : ${DOMAIN}"
echo -e "  │  Email  : ${EMAIL}"
echo -e "  └─────────────────────────────────────┘${NC}"
echo ""
read -rp "  Lanjutkan? (y/n): " CONFIRM
if [[ "$CONFIRM" != "y" && "$CONFIRM" != "Y" ]]; then
    echo -e "${RED}  Dibatalkan.${NC}"
    exit 0
fi

# ── Generate .env ─────────────────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[3/6] Membuat file .env ...${NC}"

cat > .env <<EOF
# Auto-generated by deploy-demo.sh
DOMAIN=${DOMAIN}
CORS_ORIGIN=https://${DOMAIN}
PORT=8081
EOF

echo -e "${GREEN}  ✓ .env berhasil dibuat${NC}"

# ── Generate nginx config dari template ───────────────────────────────────────
echo -e "${YELLOW}[4/6] Membuat konfigurasi Nginx ...${NC}"

mkdir -p nginx-proxy/conf.d
mkdir -p certbot/www
mkdir -p certbot/conf

# Substitusi variable ${DOMAIN} di template
export DOMAIN
envsubst '${DOMAIN}' < nginx-proxy/conf.d/default.conf.template > nginx-proxy/conf.d/default.conf

echo -e "${GREEN}  ✓ Nginx config berhasil di-generate${NC}"

# ── Request SSL Certificate ───────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[5/6] Meminta SSL certificate dari Let's Encrypt ...${NC}"
echo -e "${CYAN}  (Pastikan domain ${DOMAIN} sudah mengarah ke IP server ini!)${NC}"
echo ""

# Stop container yang mungkin pakai port 80
docker compose -f docker-compose.demo.yml down 2>/dev/null || true

# Jalankan certbot standalone untuk dapatkan sertifikat pertama kali
docker run --rm \
    -v "$(pwd)/certbot/conf:/etc/letsencrypt" \
    -v "$(pwd)/certbot/www:/var/www/certbot" \
    -p 80:80 \
    certbot/certbot certonly \
        --standalone \
        --non-interactive \
        --agree-tos \
        --email "${EMAIL}" \
        -d "${DOMAIN}" \
        --force-renewal

if [ $? -eq 0 ]; then
    echo -e "${GREEN}  ✓ SSL certificate berhasil didapatkan!${NC}"
else
    echo -e "${RED}  ✗ Gagal mendapatkan SSL certificate!${NC}"
    echo -e "${RED}    Pastikan:${NC}"
    echo -e "${RED}    - Domain sudah mengarah ke IP server ini (A record)${NC}"
    echo -e "${RED}    - Port 80 tidak dipakai proses lain${NC}"
    echo -e "${RED}    - Firewall membuka port 80 dan 443${NC}"
    exit 1
fi

# ── Build & Run Docker Compose ────────────────────────────────────────────────
echo ""
echo -e "${YELLOW}[6/6] Building & starting semua container ...${NC}"
echo ""

docker compose -f docker-compose.demo.yml up --build -d

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║                    DEPLOYMENT BERHASIL!                      ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║                                                              ║${NC}"
echo -e "${GREEN}║  URL    : https://${DOMAIN}${NC}"
echo -e "${GREEN}║  Health : https://${DOMAIN}/health${NC}"
echo -e "${GREEN}║  API    : https://${DOMAIN}/api/...${NC}"
echo -e "${GREEN}║                                                              ║${NC}"
echo -e "${GREEN}║  Logs   : docker compose -f docker-compose.demo.yml logs -f  ║${NC}"
echo -e "${GREEN}║  Stop   : docker compose -f docker-compose.demo.yml down     ║${NC}"
echo -e "${GREEN}║                                                              ║${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════════════════╝${NC}"
echo ""
echo -e "${CYAN}Tips: SSL certificate akan expired dalam 90 hari.${NC}"
echo -e "${CYAN}Untuk auto-renew, tambahkan cron job:${NC}"
echo -e "${CYAN}  0 3 * * * cd $(pwd) && docker compose -f docker-compose.demo.yml run --rm certbot renew && docker compose -f docker-compose.demo.yml exec nginx-proxy nginx -s reload${NC}"
echo ""
